name: Zappa
on: [workflow_dispatch]
jobs:
  lint:
    uses: ./.github/workflows/poetry.yml

  deploy:
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.7.1

    - name: Setup a local virtual environment (if no poetry.toml file)
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install package
      run: poetry install --with dev

    - name: Configure AWS profile
      run: |
        poetry run aws configure set region us-east-2 --profile default
        poetry run aws configure set output json --profile default
        poetry run aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
        poetry run aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default

    - name: Zappa deployments
      run: poetry run zappa update
