name: Zappa
on: [workflow_dispatch]
jobs:
  lint:
    uses: ./.github/workflows/poetry.yml

  deploy:
    needs: lint
    steps:
    - name: Configure AWS profile
      run: |
        poetry run aws configure set region us-east-2 --profile default
        poetry run aws configure set output json --profile default
        poetry run aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
        poetry run aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default

    - name: Zappa deployments
      run: poetry run zappa update
